version: "3.8"

services:
  # zookeeper:
  #   image: bitnamilegacy/zookeeper:latest
  #   environment:
  #     ALLOW_ANONYMOUS_LOGIN: "yes"
  #   networks:
  #     net2:
  #       ipv4_address: 10.6.0.18
  #   ports:
  #     - "2181:2181"

  kafka:
    image: apache/kafka:latest
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: "Mk3OEYBSD34fcwNTJENDM2Qk"
    networks:
      net2:
        ipv4_address: 10.6.0.19
    ports:
      - "9092:9092"
      - "9093:9093"

  user_postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_db
    networks:
      net2:
        ipv4_address: 10.6.0.20
    ports:
      - "5433:5432"

  order_postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders_db
    networks:
      net2:
        ipv4_address: 10.6.0.21
    ports:
      - "5434:5432"

  user_service:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:password@user_postgres:5432/users_db
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka
      - user_postgres
    networks:
      net2:
        ipv4_address: 10.6.0.22
    ports:
      - "8001:8000"
    volumes:
      - "./logs/user_service:/var/log/app"
      - "./user_service/app:/app/app"

  order_service:
    build:
      context: ./order_service
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:password@order_postgres:5432/orders_db
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka
      - user_postgres
    networks:
      net2:
        ipv4_address: 10.6.0.23
    ports:
      - "8002:8000"
    volumes:
      - "./logs/order_service:/var/log/app"
      - "./order_service/app:/app/app"

networks:
  net2:
    driver: bridge
    ipam:
      config:
        - subnet: 10.6.0.16/28
          gateway: 10.6.0.17